### ISSUE TITLE
Changing ASSET_ID breaks estimated fee.

### ISSUE THREAD

**Issue by viraladmin** [wavesfx/wavesfx#6]
Changing the Asset Name in `src/main/java/com/wavesfx/wavesfx/logic/Waves.java` and in `src/main/java/com/wavesfx/wavesfx/utils/ApplicationSettings.java` works just fine. 

Changing the Asset Id in these files however, breaks the "estimated fee" on the "Send" page. 

This doesn't APPEAR to affect mass transfer nor move assets. 

Not sure what else it affects. 

On my node I can lookup estimated fee with or without the asset Id for the default asset. 

Where can I look to find out why the default asset id is locked to "WAVES"?

**Comment by suadzh** [comment]
I'm not sure what you're trying to achieve. It's just a workaround because the endpoint does not consider Waves to be an asset.. You shouldn't modify that String.

**Comment by viraladmin** [comment]
Well thats exactly the point, I want to change the ASSET_ID. There is obviously some sort of check taking place. 

I attempted to allow the input area editable and the button enabled but it still wouldn't submit. 

So the question is, what is actually taking place that is requiring the ASSET_ID as WAVES? As you said the endpoint does not consider waves an asset so why can the ASSET_ID not be changed? There must be something taking place in the code which prevents it - some sort of api lookup, check taking place, etc -- and it seems pretty specific to the estimated fee but I may be wrong.

**Comment by suadzh** [comment]
What you're not seeing is how the old WavesJ library works when building transactions. When building a Transaction for a Waves transfer you'll have to pass `com.wavesplatform.wavesj.Asset.WAVES` (equals `"WAVES"`) from the library or an empty String. 
If you pass something else other than "WAVES", the library won't set it to null and actually make the endpoint look for the assetID `"WAVES"`. 

Long story short, either modify the WavesJ library or set `assetID` to "" (that's what I did via `.orElse("")` on MassTransfers) or `"WAVES"`. Anyway, it's a quite dirty workaround and the old WavesJ library is not being maintained anymore and WavesFX is being completely rewritten as well.
